### ISSUE TITLE
Getting Error: "could not determine kind of name for C.PyEval_ReInitThreads"

### ISSUE THREAD

**Issue by Voben** [go-python/cpy3#29]
I am trying to use the PyRun_SimpleString function for a print hello world however I am getting the error below:

../../go/pkg/mod/github.com/go-python/cpy3@v0.2.0/thread.go:53:2: could not determine kind of name for C.PyEval_ReInitThreads

This is the code that I am running.

package main

import "github.com/go-python/cpy3"

func main() {

	defer python3.Py_Finalize()
	python3.Py_Initialize()
	python3.PyRun_SimpleString("print('hello world')")
}

I am using Python 3.7.15 and have a python3,pc file.

**Comment by christian-korneck** [comment]
what Python version are you using? This library currently only works with Python 3.7. This error usually happens when trying to use a newer version of Python.

It is possible to use newer version of Python if you remove some functions from `go-python/cpy3` / `datadog/go-python3` (bindings to stuff that has been removed from Python's C-API in newer version). For example, Python 3.8 works if you remove the bindings for `PyEval_ReInitThreads`, like I did [here](https://github.com/christian-korneck/go-python3/commit/6f8fd23d06e2fa4720e79df61d86f3b694061636). More stuff might need to get removed for Python 3.9 and newer.

**Comment by Voben** [comment]
So when I run 'python --version' in the terminal, it outputs 'Python 3.7.15.' Do I need to be on an earlier version?

How would I delete the bindings. Should I download the zip of that commit or should I edit the import?

**Comment by christian-korneck** [comment]
what does `pkg-config --modversion python3` say?

**Comment by Voben** [comment]
It returns 3.8 even though version is set to 3.7 and includedir to the python3.7m folder/directory that contains the Python.h file.

**Comment by christian-korneck** [comment]
not sure why that is but you can likely get it to work by:
- create a folder with a copy of the correct `python3.pc` file
- explicitly set env var `PKG_CONFIG_PATH` to this path (i.e. `export PKG_CONFIG_PATH=/path/to/my-dir`

make sure the env var is set when you install this Go module and when you run `go build`.
(also there's a chance that you might already have a "bad" binary in your Go cache from the previous installation attempt, here `go clean -cache` and `go clean -modcache` should help).

**Comment by christian-korneck** [comment]
btw what's your OS + OS version and how did you install Python 3.7?

**Comment by Voben** [comment]
So I edited the `PKG_CONFIG_PATH` var, I hadn't specified the `pkg-config` folder but just the directory it is in. Running `pkg-config --modversion python3` now returns 3.7 as intended. After running the `go clean -cache` and `go clean -modcache` commands `go build` returns this error instead (which I have encountered before but thought I had solved by specifiying the `includedir` in the `python3.pc` file):

 `../../go/pkg/mod/github.com/go-python/cpy3@v0.2.0/boolean.go:11:10: fatal error: Python.h: No such file or directory`

And I'm running it on a WSL Ubuntu 20.04 and I believe I had installed Python using the command `sudo apt install python3.7`.

**Comment by christian-korneck** [comment]
I just tried on a vanilla Ubuntu 20.04 container and this worked for me (can't think of anything that shouldn't also be working on WSL):

```bash
docker run --name ub1 --hostname ub1 -ti ubuntu:20.04
```

and in the Ubuntu 20.04 bash shell run (all as root):

```bash
apt update
apt install wget vim
apt install git #for go get/install
apt install build-essential #gcc for cgo
apt install pkg-config #for cgo to find python includes
apt install software-properties-common #for add-apt-repository


# install latest Go (distro packages are outdated)
cd $HOME
mkdir Downloads
cd Download
wget https://go.dev/dl/go1.19.3.linux-amd64.tar.gz
rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.3.linux-amd64.tar.gz
ln -s /usr/local/go/bin/go /usr/local/bin/go

# install py 3.7 from ppa (as no distro packages for Py 3.7)
add-apt-repository ppa:deadsnakes/ppa
apt install python3.7 python3.7-dev

# we explicitly need a "python3.pc" (not "python-3.7m.pc" or so)!
cp /usr/lib/x86_64-linux-gnu/pkgconfig/python-3.7m.pc /usr/lib/x86_64-linux-gnu/pkgconfig/python3.pc
# at this point a "pkg-config --list-all" should now show a record exactly named "python3"

# create a Go test program that uses go-python/cpy3:
cd $HOME
mkdir hello
cd hello
go mod init hello
vi main.go
```

contents of main go:

```go
package main

import "github.com/go-python/cpy3"

func main() {

        defer python3.Py_Finalize()
        python3.Py_Initialize()
        python3.PyRun_SimpleString("print('hello from python in go')")

}
```

and back in the Ubuntu shell:

```
#this adds the go-python/cpy3 dep to go.mod and downloads it
go mod tidy
```

Now run the program:
```
go run .
```

Result:
```
$ root@ub1:~/hello# go run .
hello from python in go
```

**Comment by christian-korneck** [comment]
one more note: Instead of installing from the ppa deadsnakes repo you could also build Python 3.7 from source. Here's an example on Debian, it should be very similar on Ubuntu:
https://github.com/go-python/cpy3/discussions/18#discussioncomment-2951377

**Comment by Voben** [comment]
Quick question, is there an advantage to building Python 3.7 from source rather than using deadsnakes?

**Comment by christian-korneck** [comment]
technically probably not much difference. (More control and you don’t have to trust a third party package repo).

**Comment by Voben** [comment]
I'm setting up the docker container as you did, to as closely as possible trace your steps, and with the command `cp /usr/lib/x86_64-linux-gnu/pkgconfig/python-3.7m.pc /usr/lib/x86_64-linux-gnu/pkgconfig/python3.pc`, I am getting the error `cp: cannot stat '/usr/lib/x86_64-linux-gnu/pkgconfig/python3.7m.pc': No such file or directory`.

**Comment by christian-korneck** [comment]
did you install `python3.7-dev` ?

**Comment by Voben** [comment]
I found the issue, it was a stupid mistake in the directory that I missed. Continued with the rest of the commands and it worked!

Thank you so much for your help and time, I appreciate it so much!

**Comment by christian-korneck** [comment]
glad it works :)

**Comment by Zxun2** [comment]
hi christian, 

there were no issues with the installation, however when i tried to run the code i get the following error:

```
# example
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /usr/local/lib/libpython3.7m.a(floatobject.o): in function `float_rem':
/home/<username>/grpc-sample/py_script/Python-3.7.5/Objects/floatobject.c:600: undefined reference to `fmod'
/usr/bin/ld: /usr/local/lib/libpython3.7m.a(floatobject.o): in function `float_divmod':
/home/<username>/grpc-sample/py_script/Python-3.7.5/Objects/floatobject.c:629: undefined reference to `fmod'
/usr/bin/ld: /usr/local/lib/libpython3.7m.a(floatobject.o): in function `float___round___impl':
/home/<username>/grpc-sample/py_script/Python-3.7.5/Objects/floatobject.c:1055: undefined reference to `round'
/usr/bin/ld: /home/<username>/grpc-sample/py_script/Python-3.7.5/Objects/floatobject.c:1058: undefined reference to `round'
/usr/bin/ld: /usr/local/lib/libpython3.7m.a(floatobject.o): in function `float_pow':
/home/<username>/grpc-sample/py_script/Python-3.7.5/Objects/floatobject.c:728: undefined reference to `fmod'
/usr/bin/ld: /home/<username>/grpc-sample/py_script/Python-3.7.5/Objects/floatobject.c:738: undefined reference to `fmod'
/home/<username>/grpc-sample/py_script/Python-3.7.5/./Modules/posixmodule.c:5954: undefined reference to `openpty'
/usr/bin/ld: /usr/local/lib/libpython3.7m.a(posixmodule.o): in function `os_forkpty_impl':
/home/<username>/grpc-sample/py_script/Python-3.7.5/./Modules/posixmodule.c:6048: undefined reference to `forkpty'
/usr/bin/ld: /usr/local/lib/libpython3.7m.a(complexobject.o): in function `_Py_c_abs':
/home/<username>/grpc-sample/py_script/Python-3.7.5/Objects/complexobject.c:203: undefined reference to `hypot'
/usr/bin/ld: /usr/local/lib/libpython3.7m.a(complexobject.o): in function `_Py_c_pow':
/home/<username>/grpc-sample/py_script/Python-3.7.5/Objects/complexobject.c:132: undefined reference to `hypot'
/usr/bin/ld: /home/<username>/grpc-sample/py_script/Python-3.7.5/Objects/complexobject.c:133: undefined reference to `pow'
/usr/bin/ld: /home/<username>/grpc-sample/py_script/Python-3.7.5/Objects/complexobject.c:134: undefined reference to `atan2'
/usr/bin/ld: /home/<username>/grpc-sample/py_script/Python-3.7.5/Objects/complexobject.c:136: undefined reference to `sincos'
/usr/bin/ld: /home/<username>/grpc-sample/py_script/Python-3.7.5/Objects/complexobject.c:137: undefined reference to `exp'/usr/bin/ld: /home/<username>/grpc-sample/py_script/Python-3.7.5/Objects/complexobject.c:138: undefined reference to `log'
/usr/bin/ld: /usr/local/lib/libpython3.7m.a(complexobject.o): in function `_Py_c_abs':
/home/<username>/grpc-sample/py_script/Python-3.7.5/Objects/complexobject.c:203: undefined reference to `hypot'
/usr/bin/ld: /usr/local/lib/libpython3.7m.a(dynload_shlib.o): in function `_PyImport_FindSharedFuncptr':
/home/<username>/grpc-sample/py_script/Python-3.7.5/./Python/dynload_shlib.c:83: undefined reference to `dlsym'
/usr/bin/ld: /home/<username>/grpc-sample/py_script/Python-3.7.5/./Python/dynload_shlib.c:96: undefined reference to `dlopen'
/usr/bin/ld: /home/<username>/grpc-sample/py_script/Python-3.7.5/./Python/dynload_shlib.c:127: undefined reference to `dlsym'
/usr/bin/ld: /home/<username>/grpc-sample/py_script/Python-3.7.5/./Python/dynload_shlib.c:96: undefined reference to `dlopen'
/usr/bin/ld: /home/<username>/grpc-sample/py_script/Python-3.7.5/./Python/dynload_shlib.c:102: undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
```

i am using python3.7 and calling `pkg-config --modversion python3` returns 3.7
