### ISSUE TITLE
Pass arguments to a python script

### ISSUE THREAD

**Issue by subhradip-bose** [go-python/cpy3#34]
Currently PyRun_AnyFile method is taking filename  as the only argument. In case the someone wants to pass arguments to the script , can you put some thoughts how to achieve this

**Comment by christian-korneck** [comment]
I believe you can set arguments for the initialized Python interpreter with `PySys_SetArgv`. If you do this before your `PyRun_AnyFile` I believe the script you're running with it should "see" these args.

https://docs.python.org/3/c-api/init.html#c.PySys_SetArgv

**Comment by subhradip-bose** [comment]
Thanks for the guidance and its worked perfectly.

**Comment by christian-korneck** [comment]
glad to hear. :)
